#!/bin/sh
git clone /srv/git/gopherhole.git /tmp/gopherhole-clone
cd /tmp/gopherhole-clone
burrow --source /tmp/gopherhole-clone/src --destination /srv/gopher/ --spacecookie
#chown -R spacecookie:spacecookie /srv/gopher
rm -rf /tmp/gopherhole-clone
